spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/wordplay"
    username: "yardev"
    password: "yardev"
    driver-class-name: org.postgresql.Driver
  quartz:
    properties:
      org:
        quartz:
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
  liquibase:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/wordplay
    driverClassName: org.postgresql.Driver
    user: ${DB_USERNAME:yardev}
    password: ${DB_PASSWORD:yardev}
    changeLog: "classpath:db/changelog/changelog.yml"
    dropFirst: false
    enabled: true
  mvc:
    log-request-details: true
logging:
  level:
    org.springframework.web:
      DEBUG

token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
upload:
  folder: images
#  jpa:
#    generate-ddl: true
